package dependency

import (
	"path"
	"strings"
)

func svgOptions(d *discoverer, _ string, _ invocation, options []option) {
	d.context.svgOptions = append(append([]option(nil), d.context.svgOptions...), options...)
}

func svgSetup(d *discoverer, source string, call invocation) {
	svgOptions(d, source, call, parseOptions([]string{call.args[0]}))
}

func svgPath(d *discoverer, source string, call invocation) {
	value := normalizeArgument(call.args[0])
	if value != "" && !strings.HasPrefix(value, "{") {
		value = "{" + value + "}"
	}
	copyCall := call
	copyCall.args = []string{value}
	previous := d.context.graphicDirs
	graphicsPath(d, source, copyCall)
	d.context.svgDirs = d.context.graphicDirs
	d.context.graphicDirs = previous
}

func svgInput(d *discoverer, source string, call invocation) {
	values := optionValues(append(append([]option(nil), d.context.svgOptions...), parseOptions(call.options)...))
	previous := d.context.graphicDirs
	d.context.graphicDirs = append(append([]string(nil), d.context.svgDirs...), previous...)
	svg := d.consumeReference(
		source,
		call.line,
		call.name,
		normalizeArgument(call.args[0]),
		commandRegistry[call.name].rule,
	)
	d.context.graphicDirs = previous
	if svg == "" {
		return
	}
	directory := values["inkscapepath"]
	if directory == "" {
		directory = "basesubdir"
	}
	if rule, ok := svgDirectoryRegistry[directory]; ok {
		directory = rule.subdirectory
		if rule.sourceRelative {
			directory = path.Join(path.Dir(svg), directory)
		}
	}
	name := values["inkscapename"]
	if name == "" {
		name = strings.TrimSuffix(path.Base(svg), path.Ext(svg))
	}
	format := values["inkscapeformat"]
	if format == "" {
		format = "pdf"
	}
	for _, key := range []string{"inkscape", "inkscapelatex", "svgextension"} {
		if value := values[key]; value != "" && !literalReference(value) {
			d.addDiagnostic(source, call.line, call.name, value, "dynamic", "SVG selection options must be literal")
			return
		}
	}
	if extension := values["svgextension"]; extension != "" && strings.TrimPrefix(extension, ".") != "svg" {
		d.addDiagnostic(
			source,
			call.line,
			call.name,
			extension,
			"unsupported",
			"non-SVG source extensions require explicit manifest selection",
		)
		return
	}
	latex := values["inkscapelatex"] != "false"
	suffix := "_svg-raw."
	if latex {
		suffix = "_svg-tex."
	}
	if !literalReference(name) || !literalReference(format) || directory != "" && !literalReference(directory) {
		d.addDiagnostic(
			source,
			call.line,
			call.name,
			name,
			"dynamic",
			"SVG export directory, name and format must be literal",
		)
		return
	}
	if strings.HasPrefix(directory, "/") || strings.HasPrefix(name, "/") || strings.Contains(directory, ":") ||
		strings.Contains(name, ":") {
		d.addDiagnostic(
			source,
			call.line,
			call.name,
			directory+name,
			"outside_root",
			"SVG export path escapes the project root",
		)
		return
	}
	exported := path.Join(directory, name+suffix+format)
	policy := optionalFile
	if values["inkscape"] == "false" {
		policy = requiredFile
	}
	// Existing exports are upload inputs. Absent exports may be generated by
	// Inkscape; only require them statically when conversion is explicitly off.
	d.consumeReference(
		source,
		call.line,
		call.name,
		exported,
		referenceRule{extensions: []string{""}, missing: policy, rootRelative: true},
	)
	if latex {
		previousImports := d.context.importDirs
		d.context.importDirs = append([]string{path.Dir(exported), path.Dir(svg)}, previousImports...)
		d.consumeReference(
			source,
			call.line,
			call.name,
			exported+"_tex",
			referenceRule{extensions: []string{""}, recursive: true, missing: policy, rootRelative: true},
		)
		d.context.importDirs = previousImports
	}
}
